/* ============================================================================
   dsh-550w-boot — browser half.

   A CLASSIC browser script registered with the web shell's module loader. Not
   an ES module: no import, no export.

   ==========================================================================
   WHY THIS RUNS BEFORE THE APPLICATION APPEARS
   ==========================================================================

   The shell boots in this order (dsh-web-frontend, WebApp.run):

       modules = __ModuleLoader__.create(...)
       prefetchImmediateTier()        <- prefetches rows marked dsh.client.immediately
       runPluginBoot(ctx)             <- activates every enabled plugin, OURS INCLUDED
       mountApp(ctx)                  <- uiRenderer.mount(#root), the first app paint

   Plugin activation therefore happens BEFORE the application mounts, which is
   the whole reason a flash-free boot animation is possible at all: by the time
   #root is painted, the overlay is already in the document and the app is
   hidden behind a guard. `dsh.client.immediately: true` in package.json makes
   the shell prefetch this bundle during that phase instead of on first use.

   ==========================================================================
   WHY AN IFRAME AND NOT INLINE MARKUP
   ==========================================================================

   The animation is a complete standalone document: it styles `html, body`,
   sets `:root` custom properties and declares `overflow:hidden`. Inlined into
   the application's document, that stylesheet would reach the application —
   `html,body{overflow:hidden}` alone would break the shell's own scrolling —
   and the application's stylesheet would reach into the animation.

   An iframe gives both directions for free, keeps the animation's own
   setTimeout/setInterval timeline untouched (its document is an ordinary
   browser document, not this plugin's scope), and confines the animation's
   `position:fixed` wallpaper to its own viewport. Nothing about the source
   HTML has to be rewritten, which is what makes "drop in another HTML file and
   rebuild" actually work.
   ========================================================================== */
window.__ModuleLoader__.load({
  id: 'dsh-550w-boot/client',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })

    /* ---------------------------------------------------------------- *
     * Generated by build.mjs. ANIMATION is the source HTML file, JSON
     * encoded so that quotes, newlines and backslashes survive.
     * ---------------------------------------------------------------- */
    const ANIMATION = "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<title>自编译系统 · 550W 覆写与本地握手<\/title>\n<style>\n  :root{\n    --org:#f0a028;\n    --org-deep:#c97f10;\n    --org-dim:#8a5a10;\n    --bg:#050505;\n    --win-bg:#0b0b0b;\n    --txt:#d8d8d8;\n    --grn:#39c46a;\n  }\n  *{box-sizing:border-box;margin:0;padding:0;}\n  html,body{width:100%;height:100%;overflow:hidden;}\n  body{\n    background:var(--bg);\n    font-family:\"Microsoft YaHei\",\"Cascadia Code\",Consolas,monospace;\n    color:var(--txt);\n    cursor:default;\n    user-select:none;\n  }\n\n  /* ===== 顶栏 ===== */\n  #menubar{\n    height:34px;display:flex;align-items:center;gap:26px;\n    padding:0 14px;background:#000;\n    border-bottom:1px solid #1a1a1a;\n    position:relative;z-index:50;\n  }\n  #menubar .app{color:var(--org);font-size:14px;letter-spacing:1px;margin-right:12px;}\n  #menubar .mi{font-size:13px;color:#cfcfcf;padding:2px 4px;}\n  #menubar .mi:hover{background:var(--org);color:#000;}\n\n  /* ===== 工具栏 ===== */\n  #toolbar{\n    height:40px;display:flex;align-items:center;gap:8px;\n    padding:0 10px;background:#000;\n    border-bottom:2px solid var(--org);\n    position:relative;z-index:50;\n  }\n  .tbtn{\n    background:#000;color:#e8e8e8;border:1px solid #444;\n    font-size:12px;padding:5px 14px;letter-spacing:1px;\n  }\n  .tbtn.hl{background:var(--org);color:#000;border-color:var(--org);font-weight:bold;}\n  .tbtn.small{padding:5px 10px;}\n  #searchbox{\n    border:1px solid #444;background:#000;color:#888;font-size:12px;\n    padding:5px 10px;width:130px;\n  }\n  #navR{margin-left:auto;display:flex;gap:8px;}\n  #navR .tbtn{background:var(--org);color:#000;border-color:var(--org);font-weight:bold;}\n\n  /* ===== 窗口通用 ===== */\n  .win{\n    position:absolute;background:var(--win-bg);\n    border:1px solid var(--org-dim);\n    box-shadow:0 0 0 1px #000, 0 8px 30px rgba(0,0,0,.8);\n    display:none;flex-direction:column;\n    min-width:200px;\n  }\n  .win.show{display:flex;animation:winOpen .25s ease;}\n  @keyframes winOpen{from{transform:scale(.96);opacity:0;}to{transform:scale(1);opacity:1;}}\n  /* 横幅专用动画：保留 translate 居中，避免弹出瞬间跳位 */\n  #winBanner.show{animation:bannerOpen .25s ease;}\n  @keyframes bannerOpen{from{transform:translate(-50%,-50%) scale(.96);opacity:0;}to{transform:translate(-50%,-50%) scale(1);opacity:1;}}\n  .titlebar{\n    height:22px;background:var(--org);color:#1a1000;\n    display:flex;align-items:center;\n    font-size:11px;padding-left:8px;letter-spacing:1px;\n    cursor:move;flex:none;\n  }\n  .titlebar .x{\n    margin-left:auto;width:20px;height:22px;background:#e03131;color:#fff;\n    display:flex;align-items:center;justify-content:center;font-size:11px;cursor:pointer;\n  }\n  .winbody{flex:1;overflow:hidden;position:relative;}\n\n  /* ===== 日志窗 ===== */\n  #winLog{left:24px;top:92px;width:56%;height:calc(100vh - 210px);z-index:10;}\n  #logScroll{height:100%;overflow-y:hidden;padding:8px 10px;\n    font-family:Consolas,monospace;font-size:12px;line-height:1.55;color:#cfcfcf;}\n  #logScroll .pct{color:#fff;}\n  #logScroll .dir{color:#9fdfb2;}\n\n  /* ===== 系统信息窗 ===== */\n  #winInfo{right:26px;top:31%;width:300px;z-index:20;}\n  #infoBody{padding:12px 16px;font-size:12.5px;line-height:1.9;}\n  #infoBody .k{color:#e8e8e8;}\n  #infoBody .v{color:#f0f0f0;font-weight:bold;}\n  #infoBody .dev-h{margin-top:10px;color:#e8e8e8;}\n  #infoBody .dev{color:var(--org);white-space:nowrap;overflow:hidden;}\n  .caret{display:inline-block;width:7px;height:13px;background:var(--org);vertical-align:-2px;animation:blink .9s steps(1) infinite;}\n  @keyframes blink{50%{opacity:0;}}\n\n  /* ===== 背景空窗 ===== */\n  #winBg1{left:64%;top:92px;width:31%;height:32%;z-index:5;}\n  #winBg2{left:8%;top:calc(100vh - 120px);width:82%;height:70px;z-index:4;}\n\n  /* ===== 图像 Verified 状态窗 ===== */\n  #winBg1 .winbody{padding:14px 16px;font-size:12.5px;line-height:1.85;}\n  #winBg1 .vhead{color:var(--org);font-size:15px;font-weight:bold;letter-spacing:2px;}\n  #winBg1 .vtick{color:var(--grn);}\n  #winBg1 .vline{color:#e8e8e8;margin-top:6px;}\n  #winBg1 .vbar{margin-top:12px;height:6px;background:#151515;border:1px solid #333;}\n  #winBg1 .vbar i{display:block;height:100%;width:100%;background:var(--grn);box-shadow:0 0 8px rgba(57,196,106,.6);}\n  #winBg1 .vmeta{margin-top:9px;color:#9fdfb2;font-family:Consolas,monospace;letter-spacing:1px;}\n\n  /* ===== 折线图窗 ===== */\n  #winChart{left:9%;top:19%;width:80%;height:58%;z-index:15;}\n  #chartCv{width:100%;height:100%;display:block;background:#060606;}\n\n  /* ===== 覆写横幅 ===== */\n  #winBanner{\n    left:50%;top:42%;transform:translate(-50%,-50%);\n    width:620px;max-width:86vw;z-index:40;\n    border:2px solid var(--org);\n  }\n  #bannerBody{\n    padding:44px 10px;text-align:center;background:#000;\n  }\n  #bannerBody .big{\n    color:var(--org);font-size:44px;font-weight:bold;letter-spacing:22px;\n    text-shadow:0 0 22px rgba(240,160,40,.55);\n    font-family:\"Microsoft YaHei\",sans-serif;\n    white-space:nowrap;\n  }\n  #bannerBody .sub{\n    margin-top:20px;color:var(--org);font-size:17px;letter-spacing:8px;\n    font-family:\"Microsoft YaHei\",sans-serif;\n    opacity:0;transition:opacity .6s;\n  }\n  #bannerBody .sub.show{opacity:1;}\n\n  /* ===== 重播 & 时间码 ===== */\n  #replay{\n    position:fixed;right:14px;bottom:12px;z-index:60;\n    background:#000;color:var(--org);border:1px solid var(--org);\n    font-size:12px;padding:6px 16px;letter-spacing:2px;cursor:pointer;\n    font-family:inherit;display:none;\n  }\n  #replay.show{display:block;}\n  #replay:hover{background:var(--org);color:#000;}\n  #tc{\n    position:fixed;left:14px;bottom:12px;z-index:60;\n    color:#555;font-size:11px;letter-spacing:2px;font-family:Consolas,monospace;\n  }\n  ::-webkit-scrollbar{width:8px;background:#0b0b0b;}\n  ::-webkit-scrollbar-thumb{background:var(--org-dim);}\n<\/style>\n<\/head>\n<body>\n\n<div id=\"menubar\">\n  <span class=\"app\">自编译系统<\/span>\n  <span class=\"mi\">文件<\/span><span class=\"mi\">编辑<\/span><span class=\"mi\">视图<\/span>\n  <span class=\"mi\">工程<\/span><span class=\"mi\">调试<\/span><span class=\"mi\">测试<\/span>\n  <span class=\"mi\">分析<\/span><span class=\"mi\">窗口<\/span><span class=\"mi\">帮助<\/span>\n<\/div>\n\n<div id=\"toolbar\">\n  <button class=\"tbtn\" style=\"min-width:150px;\">本地系统调试器 ▾<\/button>\n  <button class=\"tbtn hl\">自动 ▾<\/button>\n  <button class=\"tbtn\">调试 ▾<\/button>\n  <button class=\"tbtn\">测试 ▾<\/button>\n  <button class=\"tbtn small\">网络<\/button>\n  <button class=\"tbtn small\">节点<\/button>\n  <button class=\"tbtn small\">日志<\/button>\n  <input id=\"searchbox\" placeholder=\"搜索\">\n  <div id=\"navR\">\n    <span class=\"tbtn navCode\">UEG联合政府<\/span>\n  <\/div>\n<\/div>\n\n<!-- 背景空窗 -->\n<div class=\"win\" id=\"winBg1\">\n  <div class=\"titlebar\">图像 Verified 行<span class=\"x\">✕<\/span><\/div>\n  <div class=\"winbody\" id=\"bg1Body\">\n    <div class=\"vstat\">\n      <div class=\"vhead\">VERIFIED <span class=\"vtick\">✓<\/span><\/div>\n      <div class=\"vline\">镜像完整性校验通过<\/div>\n      <div class=\"vbar\"><i><\/i><\/div>\n      <div class=\"vmeta\">校验项 128 / 128 · SHA-256 匹配<\/div>\n    <\/div>\n  <\/div>\n<\/div>\n<div class=\"win\" id=\"winBg2\">\n  <div class=\"titlebar\">内核 缓冲 行<span class=\"x\">✕<\/span><\/div>\n  <div class=\"winbody\"><\/div>\n<\/div>\n\n<!-- 生成日志窗 -->\n<div class=\"win\" id=\"winLog\">\n  <div class=\"titlebar\">图像 Verified 行<span class=\"x\">✕<\/span><\/div>\n  <div class=\"winbody\"><div id=\"logScroll\"><\/div><\/div>\n<\/div>\n\n<!-- 系统信息窗 -->\n<div class=\"win\" id=\"winInfo\">\n  <div class=\"titlebar\">系统 属性 概述<span class=\"x\">✕<\/span><\/div>\n  <div class=\"winbody\"><div id=\"infoBody\"><\/div><\/div>\n<\/div>\n\n<!-- 折线图窗 -->\n<div class=\"win\" id=\"winChart\">\n  <div class=\"titlebar\">渲染 负载 波形<span class=\"x\">✕<\/span><\/div>\n  <div class=\"winbody\"><canvas id=\"chartCv\"><\/canvas><\/div>\n<\/div>\n\n<!-- 覆写横幅 -->\n<div class=\"win\" id=\"winBanner\">\n  <div class=\"titlebar\">系统 控制权 通知<span class=\"x\">✕<\/span><\/div>\n  <div class=\"winbody\" id=\"bannerBody\">\n    <div class=\"big\" id=\"bannerCode\" style=\"letter-spacing:10px;margin-bottom:18px;\">550W<\/div>\n    <div class=\"big\">系统已覆写<\/div>\n    <div class=\"sub\" id=\"bannerSub\">本地握手成功<\/div>\n  <\/div>\n<\/div>\n\n<div id=\"tc\">550W:23.0.055.0&nbsp;&nbsp;|&nbsp;&nbsp;LINK:--<\/div>\n<button id=\"replay\">▶ 重新执行<\/button>\n\n<script>\n/* ================= 工具：拖动窗口 ================= */\ndocument.querySelectorAll('.win').forEach(w=>{\n  const bar=w.querySelector('.titlebar');\n  bar.addEventListener('mousedown',e=>{\n    if(e.target.classList.contains('x'))return;\n    const r=w.getBoundingClientRect(),ox=e.clientX-r.left,oy=e.clientY-r.top;\n    w.style.left=r.left+'px';w.style.top=r.top+'px';w.style.right='auto';w.style.transform='none';\n    const mv=ev=>{w.style.left=(ev.clientX-ox)+'px';w.style.top=(ev.clientY-oy)+'px';};\n    const up=()=>{removeEventListener('mousemove',mv);removeEventListener('mouseup',up);};\n    addEventListener('mousemove',mv);addEventListener('mouseup',up);\n  });\n  w.querySelector('.x').addEventListener('click',()=>w.classList.remove('show'));\n});\n\n/* ================= 日志生成 ================= */\nconst NAMES=[\n \"VirtualSurroundAppl.dll\",\"nsis.dll\",\"Microsoft.WindowsSearch.Commands.Resources.dll\",\"NOF\",\n \"c_fsactivitymonitor.inf\",\"xwizard.exe\",\"wifidisplay.dll\",\"ndisharev4.gpd\",\"whrnm.ini\",\n \"TigerKekePECH-LP.cot\",\"Education-OEM-DM-2-ul-qob-test-xrm-ms\",\"ndsVirtualBus.inf_amd64_9956f922e32dase\",\n \"MigratedVcsOneDrive 目录\",\"Hyper-V-KernelVSP-Package-3fbf3856ad364e35-amd64--zh-CN-10.0.2\",\n \"V_coreActivation_zh-CN.dat\",\"WMPPhoto.dll\",\"WindowsFoldersControl.dll\",\n \"Windows-Hyper-V-OptionalFeature-HypervisorPlatform-Disa\",\"sheres.dll\",\"wircortex.ini\",\n \"netr7366.inf_amd64_93 2fd468e5f30d4\",\"SPowerShelV1.0.0.Modules|Microsoft.PowerShell.LocalAccounts\\1.0.0\\lfr\",\n \"dmusic.dll.mui\",\"ucbhd.inf_amd64_7437d5bdf59b5b24\",\"Restore\",\"syscoli.dll\",\"cortana_es-ES_hdsp\",\n \"Hyper-V-Networking-VirtualDevice-Synthetic-merged-Package\",\"WsoExt.dll\",\"kbd101.dll\",\"mdmfs6S.inf\",\n \"Microsoft-Windows-WordPad-FoD-Package\",\"[05E92F4D-C044-492A-81EC-0B7IC7689462).catalogitem\",\"fw\",\n \"tzsync.exe\",\"dfrgui.exe\",\"mfx_hnf_h265ve_32.dll\",\"tclkhlostw.exe\",\"gpmrefr_fr-FR.mui\",\"modemosinf\",\n \"Ntseyvr.lnt\",\"TpmTasks.dll.mui\",\"UsageDataFlushing\"\n];\nconst logEl=document.getElementById('logScroll');\nlet genTimer=null;\n\nfunction logLine(){\n  const pct=LOG_STATE.p;\n  const size=(Math.random()*8000+500).toFixed(0).replace(/\\B(?=(\\d{3})+(?!\\d))/g,\",\");\n  const name=NAMES[Math.floor(Math.random()*NAMES.length)];\n  const d=document.createElement('div');\n  const roll=Math.random();\n  if(roll<0.06){\n    d.innerHTML=`<span class=\"pct\">${pct.toFixed(1)}%&nbsp;&nbsp;<\/span><span class=\"dir\">GENERATING 目录<\/span>`;\n  }else if(roll<0.12){\n    d.innerHTML=`<span class=\"pct\">${pct.toFixed(1)}%&nbsp;&nbsp;<\/span>GENERATING ...`;\n  }else{\n    d.innerHTML=`<span class=\"pct\">${pct.toFixed(1)}%&nbsp;&nbsp;<\/span>GENERATING ${size} ${name}`;\n  }\n  logEl.appendChild(d);\n  while(logEl.children.length>60)logEl.removeChild(logEl.firstChild);\n  logEl.scrollTop=logEl.scrollHeight;\n}\n\n/* ================= 系统信息打字 ================= */\nconst INFO=[\n ['操作系统：','550W底层'],\n ['版本:','23.0.055.0'],\n ['所有者：','地球联合政府'],\n ['CPU L1缓存:','152GB'],\n ['图形化显存:','48TB'],\n ['最大渲染能力:','128x MSAA'],\n];\nconst DEVICES=[\n '地球联合政府 无人及控制系统',\n '地球联合政府 敌我识别系统',\n '地球联合政府 主动防御',\n '地球联合政府 太空电梯控制',\n '地球联合政府 月球发动机控制',\n '地球联合政府 领航者空间站',\n '地球联合政府 行星发动机控制',\n];\nconst infoBody=document.getElementById('infoBody');\nfunction typeInfo(done){\n  let i=0,j=0;\n  let cur=null;\n  (function step(){\n    if(i<INFO.length){\n      if(j===0){cur=document.createElement('div');infoBody.appendChild(cur);}\n      cur.innerHTML=`<span class=\"k\">${INFO[i][0]}<\/span><span class=\"v\">${INFO[i][1].slice(0,j)}<\/span><span class=\"caret\"><\/span>`;\n      j++;\n        if(j>INFO[i][1].length){i++;j=0;setTimeout(step,80);}\n        else setTimeout(step,16);\n      }else{\n        const h=document.createElement('div');\n        h.className='dev-h';h.textContent='已挂载设备:';\n        infoBody.appendChild(h);\n        let k=0;\n        (function dev(){\n          if(k>=DEVICES.length){done&&done();return;}\n          const d=document.createElement('div');\n          d.className='dev';d.textContent=DEVICES[k];\n          infoBody.appendChild(d);k++;\n          setTimeout(dev,130);\n        })();\n    }\n  })();\n}\n\n/* ================= 折线图 ================= */\nconst cv=document.getElementById('chartCv'),cx=cv.getContext('2d');\nlet chartOn=false,pts=[],tPhase=0;\nfunction fitCanvas(){\n  const r=cv.getBoundingClientRect();\n  cv.width=r.width;cv.height=r.height;\n}\naddEventListener('resize',fitCanvas);\nfunction drawChart(){\n  if(!chartOn)return;\n  fitCanvas();\n  const W=cv.width,H=cv.height;\n  cx.fillStyle='#060606';cx.fillRect(0,0,W,H);\n  cx.strokeStyle='#1c1c1c';cx.lineWidth=1;\n  for(let y=30;y<H;y+=46){cx.beginPath();cx.moveTo(0,y);cx.lineTo(W,y);cx.stroke();}\n  cx.strokeStyle='#2a2a2a';\n  for(let x=60;x<W;x+=120){cx.beginPath();cx.moveTo(x,0);cx.lineTo(x,H);cx.stroke();}\n  // 波形：前段剧烈震荡，后段趋稳（代表系统被逐步接管）\n  tPhase++;\n  const target = tPhase<140 ? (Math.random()*0.9+0.05) : 0.62+(Math.random()-0.5)*0.06;\n  pts.push(target);\n  if(pts.length>90)pts.shift();\n  cx.strokeStyle='#2f9e55';cx.lineWidth=1.6;\n  cx.beginPath();\n  pts.forEach((v,i)=>{\n    const x=(i/(90-1))*W, y=H-20-v*(H-50);\n    i?cx.lineTo(x,y):cx.moveTo(x,y);\n  });\n  cx.stroke();\n  cx.fillStyle='#39c46a';\n  pts.forEach((v,i)=>{\n    const x=(i/(90-1))*W, y=H-20-v*(H-50);\n    if(i%3===0){cx.beginPath();cx.arc(x,y,3,0,7);cx.fill();}\n  });\n  requestAnimationFrame(drawChart);\n}\n\n/* ================= 主时间线 ================= */\nconst LOG_STATE={p:0};\nconst LINK=document.getElementById('tc');\n/* show 提升为全局，供 run() 与 openBanner() 共用 */\nconst show=(id,d)=>setTimeout(()=>document.getElementById(id).classList.add('show'),d);\nfunction run(){\n  // 复位\n  document.querySelectorAll('.win').forEach(w=>w.classList.remove('show'));\n  logEl.innerHTML='';infoBody.innerHTML='';\n  document.getElementById('bannerSub').classList.remove('show');\n  document.getElementById('replay').classList.remove('show');\n  pts=[];tPhase=0;chartOn=false;\n  LOG_STATE.p=0;\n  clearInterval(genTimer);\n\n  show('winBg1',150);\n  show('winBg2',200);\n  show('winLog',280);\n\n  // 日志推进：0→100，约 2.8 秒快滚\n  setTimeout(()=>{\n    genTimer=setInterval(()=>{\n      LOG_STATE.p+=Math.random()*1.7+0.9;\n      if(LOG_STATE.p>=100){\n        LOG_STATE.p=100;\n        clearInterval(genTimer);\n        logLine();\n        setTimeout(openBanner,180);\n      }\n      logLine();\n    },38);\n  },320);\n\n  // 系统信息窗\n  setTimeout(()=>{show('winInfo',0);typeInfo();},950);\n  LINK.textContent='LINK:握手建立中';\n\n  // 折线图窗\n  setTimeout(()=>{show('winChart',0);fitCanvas();chartOn=true;drawChart();},1500);\n}\n\nfunction openBanner(){\n  // 100% 后让中央图表窗与背景空窗退场、停止绘制，把焦点交给横幅\n  chartOn=false;\n  document.getElementById('winChart').classList.remove('show');\n  document.getElementById('winBg1').classList.remove('show');\n  document.getElementById('winBg2').classList.remove('show');\n  show('winBanner',0);\n  LINK.textContent='LINK:已覆写 · 加密';\n  setTimeout(()=>{\n    document.getElementById('bannerSub').classList.add('show');\n    document.getElementById('replay').classList.add('show');\n  },800);\n}\n\ndocument.getElementById('replay').addEventListener('click',run);\nrun();\n<\/script>\n<\/body>\n<\/html>\n"
    const OPTIONS = {"enabled":true,"durationMs":6600,"fadeMs":700,"hintDelayMs":1400,"hint":"550W 正在接入 · 点击任意处跳过","skipOnAnyKey":true,"timerSlackMs":400}
    const BUILD = {"version":"1.0.0","source":"550W_ui.html","animationBytes":15997,"animationSha256":"724389750848","builtAt":"2026-10-05T00:40:52.525Z"}
    /* ---------------------------------------------------------------- */

    const OVERLAY_ID = 'dsh-550w-boot-overlay'
    const FRAME_ID = 'dsh-550w-boot-frame'
    const CATCHER_ID = 'dsh-550w-boot-catcher'
    const HINT_ID = 'dsh-550w-boot-hint'
    const GUARD_ID = 'dsh-550w-boot-guard'
    const SESSION_FLAG = '__DSH_550W_BOOT_DONE__'

    /* ---------------------------------------------------------------- *
     * Scheduling.
     *
     * Every deadline here is armed twice: once on a requestAnimationFrame
     * chain, once on a plain timer, and the first one to arrive wins.
     *
     * The frame chain is what makes the timing frame-accurate while the window
     * is being painted — the case that matters, because the animation is the
     * only thing on screen and nothing competes for frames.
     *
     * The timer is what keeps a stalled frame loop from becoming a hidden
     * application. rAF does not advance while the window is hidden or fully
     * occluded (Chromium throttles it to nothing), and a compositor that stops
     * producing frames stops it just as completely. Without the timer path,
     * "the animation never finishes" would mean "#root stays hidden forever",
     * which is the one failure this plugin must not have. Timers keep running
     * in a hidden page, throttled to roughly once a second, which is enough to
     * reveal the application late rather than never.
     *
     * The deadline is wall-clock based in both paths, not a count of frames, so
     * a slow first paint cannot stretch the animation. And the timer carries a
     * little slack, so the frame-accurate path wins whenever frames are running
     * at all.
     * ---------------------------------------------------------------- */
    const now = () => {
      try {
        if (typeof performance === 'object' && performance && typeof performance.now === 'function') {
          return performance.now()
        }
      } catch { /* fall through */ }
      return Date.now()
    }

    const after = (ms, fn) => {
      const started = now()
      let rafId = 0
      let timer = 0
      let done = false

      const fire = () => {
        if (done) return
        done = true
        if (rafId) { try { window.cancelAnimationFrame(rafId) } catch { /* nothing to do */ } }
        if (timer) { try { window.clearTimeout(timer) } catch { /* nothing to do */ } }
        fn()
      }

      const step = () => {
        if (done) return
        if (now() - started >= ms) { fire(); return }
        rafId = window.requestAnimationFrame(step)
      }
      rafId = window.requestAnimationFrame(step)

      try {
        timer = window.setTimeout(fire, ms + OPTIONS.timerSlackMs)
      } catch { /* no timer available; the frame chain is then the only path */ }

      /* Idempotent cancel: never runs fn. */
      return () => {
        done = true
        if (rafId) { try { window.cancelAnimationFrame(rafId) } catch { /* nothing to do */ } }
        if (timer) { try { window.clearTimeout(timer) } catch { /* nothing to do */ } }
      }
    }

    /* The guard: hide the application until the animation is done.
     *
     * `visibility:hidden` rather than `display:none` is deliberate. The shell's
     * theme presenter measures the rendered background as its colour authority
     * and the layout frame measures its columns; a display:none subtree has no
     * boxes to measure and would report zeros. A visibility:hidden subtree
     * keeps its layout, so every measurement the application takes while the
     * animation plays returns the same numbers it would have returned without
     * this plugin. */
    const installGuard = () => {
      if (document.getElementById(GUARD_ID)) return
      const style = document.createElement('style')
      style.id = GUARD_ID
      style.textContent = '#root{visibility:hidden !important}'
      const host = document.head || document.documentElement
      if (host) host.appendChild(style)
    }

    const removeGuard = () => {
      const style = document.getElementById(GUARD_ID)
      if (style && style.parentNode) style.parentNode.removeChild(style)
    }

    /* Build the overlay. Returns the handles the lifecycle needs, so nothing
     * has to be looked up again while the animation is running. */
    const buildOverlay = () => {
      const overlay = document.createElement('div')
      overlay.id = OVERLAY_ID
      /* The animation is decorative; a screen reader should hear the app, not
       * this. The iframe carries no accessible name for the same reason. */
      overlay.setAttribute('aria-hidden', 'true')
      overlay.setAttribute('role', 'presentation')

      const os = overlay.style
      os.position = 'fixed'
      os.top = '0'
      os.left = '0'
      os.right = '0'
      os.bottom = '0'
      os.width = '100%'
      os.height = '100%'
      /* Above every application layer. The shell's own overlays (toasts,
       * dialogs, the command palette) sit in the low thousands. */
      os.zIndex = '2147483000'
      os.background = '#050505'
      os.opacity = '1'
      os.transition = 'opacity ' + OPTIONS.fadeMs + 'ms ease'
      os.pointerEvents = 'auto'
      os.overflow = 'hidden'

      const frame = document.createElement('iframe')
      frame.id = FRAME_ID
      frame.setAttribute('title', '')
      frame.setAttribute('tabindex', '-1')
      frame.setAttribute('scrolling', 'no')
      frame.setAttribute('frameborder', '0')
      /* No sandbox attribute: the animation is our own inline document and
       * needs its scripts, and any sandbox token set here would make the frame
       * cross-origin. */
      const fss = frame.style
      fss.position = 'absolute'
      fss.top = '0'
      fss.left = '0'
      fss.width = '100%'
      fss.height = '100%'
      fss.border = '0'
      fss.display = 'block'
      fss.background = '#050505'

      /* srcdoc is the direct route; a data URL is the fallback for an engine
       * without it. Both give the frame a document of its own. */
      if ('srcdoc' in frame) {
        frame.srcdoc = ANIMATION
      } else {
        frame.src = 'data:text/html;charset=utf-8,' + encodeURIComponent(ANIMATION)
      }
      overlay.appendChild(frame)

      /* A transparent catcher above the frame. Without it every click lands in
       * the animation's document — where it would drag a window around
       * instead of skipping the splash. The animation is a splash here, not an
       * application, so owning the pointer is the correct trade. */
      const catcher = document.createElement('div')
      catcher.id = CATCHER_ID
      const css = catcher.style
      css.position = 'absolute'
      css.top = '0'
      css.left = '0'
      css.right = '0'
      css.bottom = '0'
      css.background = 'transparent'
      css.cursor = 'pointer'
      overlay.appendChild(catcher)

      const hint = document.createElement('div')
      hint.id = HINT_ID
      hint.textContent = OPTIONS.hint
      const hs = hint.style
      hs.position = 'absolute'
      hs.right = '16px'
      hs.bottom = '14px'
      hs.color = '#8a5a10'
      hs.font = '12px/1.6 "Microsoft YaHei", "Cascadia Code", Consolas, monospace'
      hs.letterSpacing = '2px'
      hs.opacity = '0'
      hs.transition = 'opacity 600ms ease'
      hs.pointerEvents = 'none'
      overlay.appendChild(hint)

      return { overlay, frame, catcher, hint }
    }

    /* Play once per page load, then get out of the way.
     *
     * Returns a disposer so that unloading the plugin (or an HMR rebuild) takes
     * the overlay and the guard with it. Leaving the guard behind would hide
     * the application with nothing left to reveal it, which is the one failure
     * mode this plugin must not have. */
    const play = (label) => {
      if (window[SESSION_FLAG]) {
        // eslint-disable-next-line no-console
        console.log('[boot550w] v' + BUILD.version + ' already played in this page load; not replaying')
        return () => {}
      }

      installGuard()

      const root = document.body || document.documentElement
      if (!root) throw new Error('no document body to attach the overlay to')

      const { overlay, catcher, hint } = buildOverlay()
      root.appendChild(overlay)

      /* Written only once the overlay is really in the document, so a failure
       * above does not mark the page as "already played". */
      window[SESSION_FLAG] = true

      const started = now()
      let finished = false
      let cancelDeadline = () => {}
      let cancelHint = () => {}

      const cleanup = () => {
        cancelDeadline()
        cancelHint()
        window.removeEventListener('keydown', onKey, true)
        window.removeEventListener('pointerdown', onPointer, true)
        catcher.removeEventListener('click', onPointer)
      }

      const finish = (why) => {
        if (finished) return
        finished = true
        cleanup()

        /* The guard lifts as the fade starts, so the application cross-fades in
         * underneath rather than appearing after a black frame. */
        removeGuard()
        overlay.style.opacity = '0'

        const drop = () => {
          if (overlay.parentNode) overlay.parentNode.removeChild(overlay)
          // eslint-disable-next-line no-console
          console.log('[boot550w] v' + BUILD.version + ' overlay removed after '
            + Math.round(now() - started) + 'ms (' + why + ')')
        }
        after(OPTIONS.fadeMs + 40, drop)
      }

      const onPointer = () => { finish('skipped by pointer') }
      const onKey = (event) => {
        /* Modifier-only presses are not a decision to skip. */
        if (event.key === 'Shift' || event.key === 'Control' || event.key === 'Alt' || event.key === 'Meta') return
        finish('skipped by key ' + JSON.stringify(event.key))
      }

      catcher.addEventListener('click', onPointer)
      window.addEventListener('pointerdown', onPointer, true)
      if (OPTIONS.skipOnAnyKey) window.addEventListener('keydown', onKey, true)

      cancelHint = after(OPTIONS.hintDelayMs, () => { hint.style.opacity = '1' })
      cancelDeadline = after(OPTIONS.durationMs, () => { finish('animation finished') })

      // eslint-disable-next-line no-console
      console.log('[boot550w] v' + BUILD.version + ' overlay mounted from ' + label
        + ' | animation ' + BUILD.animationBytes + ' bytes, duration '
        + OPTIONS.durationMs + 'ms, fade ' + OPTIONS.fadeMs + 'ms')

      return () => {
        cleanup()
        removeGuard()
        if (overlay.parentNode) overlay.parentNode.removeChild(overlay)
      }
    }

    const plugin = {
      name: 'boot550w',
      /* Nothing is injected: this plugin reads no service, and the DOM APIs it
       * uses are not services. cordis refuses a service that was not declared,
       * so an empty inject list is the honest declaration. */
      inject: [],
      apply(ctx) {
        let disposeOverlay = () => {}
        try {
          disposeOverlay = play('plugin activation')
        } catch (error) {
          /* A splash screen is never a reason for the application to fail to
           * start. Reveal the app and say so. */
          removeGuard()
          // eslint-disable-next-line no-console
          console.error('[boot550w] overlay failed, continuing without it', error)
        }

        if (ctx && typeof ctx.effect === 'function') {
          ctx.effect(() => () => {
            try { disposeOverlay() } catch { /* teardown must not throw */ }
          }, 'dsh-550w-boot: overlay')
        }

        /* Console escape hatch: `__dsh550w.skip()` ends the splash, and
         * `__dsh550w.play()` replays it without a restart. */
        try {
          window.__dsh550w = {
            version: BUILD.version,
            options: OPTIONS,
            skip: () => {
              const catcher = document.getElementById(CATCHER_ID)
              if (catcher) catcher.click()
            },
            play: () => {
              delete window[SESSION_FLAG]
              installGuard()
              play('console replay')
            },
            reveal: removeGuard,
          }
        } catch { /* the handle is a convenience, not a contract */ }
      },
    }

    exports.default = plugin
    exports.plugin = plugin
    exports.apply = plugin.apply
    exports.name = plugin.name
    exports.inject = plugin.inject

    return module.exports
  },
})
